// State/district lists are authoritative and complete (28 states + 8 UTs, ~2024 divisions); city lists per district are a representative/best-effort sample of major towns, not exhaustive.

export interface IndiaDistrict {
  name: string;
  cities: string[];
}

export interface IndiaState {
  name: string;
  districts: IndiaDistrict[];
}

export const indiaLocations: IndiaState[] = [
  {
    name: "Andhra Pradesh",
    districts: [
      { name: "Alluri Sitharama Raju", cities: ["Paderu", "Araku Valley", "Chintapalle"] },
      { name: "Anakapalli", cities: ["Anakapalli", "Narsipatnam", "Yelamanchili"] },
      { name: "Ananthapuramu", cities: ["Anantapur", "Hindupur", "Guntakal", "Dharmavaram"] },
      { name: "Annamayya", cities: ["Rayachoti", "Madanapalle", "Rajampet"] },
      { name: "Bapatla", cities: ["Bapatla", "Chirala", "Repalle"] },
      { name: "Chittoor", cities: ["Chittoor", "Puttur", "Palamaner"] },
      { name: "Dr. B.R. Ambedkar Konaseema", cities: ["Amalapuram", "Razole", "Mummidivaram"] },
      { name: "East Godavari", cities: ["Kakinada", "Rajahmundry", "Peddapuram"] },
      { name: "Eluru", cities: ["Eluru", "Jangareddygudem", "Nuzvid"] },
      { name: "Guntur", cities: ["Guntur", "Tenali", "Mangalagiri"] },
      { name: "Kakinada", cities: ["Kakinada", "Pithapuram", "Samalkota"] },
      { name: "Krishna", cities: ["Machilipatnam", "Gudivada", "Vuyyuru"] },
      { name: "Kurnool", cities: ["Kurnool", "Nandyal", "Adoni"] },
      { name: "Nandyal", cities: ["Nandyal", "Allagadda", "Dhone"] },
      { name: "NTR", cities: ["Vijayawada", "Nandigama", "Jaggayyapeta"] },
      { name: "Palnadu", cities: ["Narasaraopet", "Sattenapalle", "Gurazala"] },
      { name: "Parvathipuram Manyam", cities: ["Parvathipuram", "Salur", "Bobbili"] },
      { name: "Prakasam", cities: ["Ongole", "Markapur", "Kandukur"] },
      { name: "Sri Potti Sriramulu Nellore", cities: ["Nellore", "Kavali", "Gudur"] },
      { name: "Sri Sathya Sai", cities: ["Puttaparthi", "Penukonda", "Kadiri"] },
      { name: "Srikakulam", cities: ["Srikakulam", "Amadalavalasa", "Palasa"] },
      { name: "Tirupati", cities: ["Tirupati", "Srikalahasti", "Naidupeta"] },
      { name: "Visakhapatnam", cities: ["Visakhapatnam", "Bheemunipatnam", "Anandapuram"] },
      { name: "Vizianagaram", cities: ["Vizianagaram", "Bobbili", "Cheepurupalli"] },
      { name: "West Godavari", cities: ["Bhimavaram", "Tadepalligudem", "Palakollu"] },
      { name: "YSR Kadapa", cities: ["Kadapa", "Proddatur", "Pulivendla"] },
    ],
  },
  {
    name: "Arunachal Pradesh",
    districts: [
      { name: "Anjaw", cities: ["Hawai"] },
      { name: "Changlang", cities: ["Changlang", "Miao", "Jairampur"] },
      { name: "Dibang Valley", cities: ["Anini"] },
      { name: "East Kameng", cities: ["Seppa"] },
      { name: "East Siang", cities: ["Pasighat"] },
      { name: "Kamle", cities: ["Raga"] },
      { name: "Kra Daadi", cities: ["Jamin"] },
      { name: "Kurung Kumey", cities: ["Koloriang"] },
      { name: "Lepa Rada", cities: ["Basar"] },
      { name: "Lohit", cities: ["Tezu"] },
      { name: "Longding", cities: ["Longding"] },
      { name: "Lower Dibang Valley", cities: ["Roing"] },
      { name: "Lower Siang", cities: ["Likabali"] },
      { name: "Lower Subansiri", cities: ["Ziro"] },
      { name: "Namsai", cities: ["Namsai", "Chowkham"] },
      { name: "Pakke-Kessang", cities: ["Pakke-Kessang"] },
      { name: "Papum Pare", cities: ["Yupia", "Itanagar", "Naharlagun"] },
      { name: "Shi Yomi", cities: ["Tato"] },
      { name: "Siang", cities: ["Boleng"] },
      { name: "Tawang", cities: ["Tawang"] },
      { name: "Tirap", cities: ["Khonsa"] },
      { name: "Upper Dibang Valley", cities: ["Anini"] },
      { name: "Upper Siang", cities: ["Yingkiong"] },
      { name: "Upper Subansiri", cities: ["Daporijo"] },
      { name: "West Kameng", cities: ["Bomdila"] },
      { name: "West Siang", cities: ["Aalo"] },
    ],
  },
  {
    name: "Assam",
    districts: [
      { name: "Bajali", cities: ["Pathsala"] },
      { name: "Baksa", cities: ["Mushalpur"] },
      { name: "Barpeta", cities: ["Barpeta", "Barpeta Road"] },
      { name: "Biswanath", cities: ["Biswanath Chariali"] },
      { name: "Bongaigaon", cities: ["Bongaigaon", "Abhayapuri"] },
      { name: "Cachar", cities: ["Silchar", "Lakhipur", "Sonai"] },
      { name: "Charaideo", cities: ["Sonari"] },
      { name: "Chirang", cities: ["Kajalgaon"] },
      { name: "Darrang", cities: ["Mangaldai"] },
      { name: "Dhemaji", cities: ["Dhemaji"] },
      { name: "Dhubri", cities: ["Dhubri", "Gauripur"] },
      { name: "Dibrugarh", cities: ["Dibrugarh", "Naharkatia", "Chabua"] },
      { name: "Dima Hasao", cities: ["Haflong"] },
      { name: "Goalpara", cities: ["Goalpara"] },
      { name: "Golaghat", cities: ["Golaghat", "Bokakhat"] },
      { name: "Hailakandi", cities: ["Hailakandi"] },
      { name: "Hojai", cities: ["Hojai", "Lanka"] },
      { name: "Jorhat", cities: ["Jorhat", "Titabar"] },
      { name: "Kamrup", cities: ["Amingaon", "Rangia", "Boko"] },
      { name: "Kamrup Metropolitan", cities: ["Guwahati", "Dispur"] },
      { name: "Karbi Anglong", cities: ["Diphu"] },
      { name: "Karimganj", cities: ["Karimganj", "Badarpur"] },
      { name: "Kokrajhar", cities: ["Kokrajhar", "Gossaigaon"] },
      { name: "Lakhimpur", cities: ["North Lakhimpur"] },
      { name: "Majuli", cities: ["Garamur"] },
      { name: "Morigaon", cities: ["Morigaon", "Jagiroad"] },
      { name: "Nagaon", cities: ["Nagaon", "Kaliabor"] },
      { name: "Nalbari", cities: ["Nalbari"] },
      { name: "Sivasagar", cities: ["Sivasagar", "Nazira"] },
      { name: "Sonitpur", cities: ["Tezpur"] },
      { name: "South Salmara-Mankachar", cities: ["Hatsingimari"] },
      { name: "Tamulpur", cities: ["Tamulpur"] },
      { name: "Tinsukia", cities: ["Tinsukia", "Digboi", "Margherita"] },
      { name: "Udalguri", cities: ["Udalguri"] },
      { name: "West Karbi Anglong", cities: ["Hamren"] },
    ],
  },
  {
    name: "Bihar",
    districts: [
      { name: "Araria", cities: ["Araria", "Forbesganj", "Jogbani"] },
      { name: "Arwal", cities: ["Arwal"] },
      { name: "Aurangabad", cities: ["Aurangabad", "Daudnagar"] },
      { name: "Banka", cities: ["Banka"] },
      { name: "Begusarai", cities: ["Begusarai", "Barauni"] },
      { name: "Bhagalpur", cities: ["Bhagalpur", "Naugachhia"] },
      { name: "Bhojpur", cities: ["Ara", "Piro"] },
      { name: "Buxar", cities: ["Buxar", "Dumraon"] },
      { name: "Darbhanga", cities: ["Darbhanga", "Benipur"] },
      { name: "East Champaran", cities: ["Motihari", "Raxaul"] },
      { name: "Gaya", cities: ["Gaya", "Bodh Gaya", "Sherghati"] },
      { name: "Gopalganj", cities: ["Gopalganj"] },
      { name: "Jamui", cities: ["Jamui"] },
      { name: "Jehanabad", cities: ["Jehanabad"] },
      { name: "Kaimur", cities: ["Bhabhua"] },
      { name: "Katihar", cities: ["Katihar", "Manihari"] },
      { name: "Khagaria", cities: ["Khagaria"] },
      { name: "Kishanganj", cities: ["Kishanganj"] },
      { name: "Lakhisarai", cities: ["Lakhisarai"] },
      { name: "Madhepura", cities: ["Madhepura"] },
      { name: "Madhubani", cities: ["Madhubani", "Jhanjharpur"] },
      { name: "Munger", cities: ["Munger", "Jamalpur"] },
      { name: "Muzaffarpur", cities: ["Muzaffarpur", "Motipur"] },
      { name: "Nalanda", cities: ["Bihar Sharif", "Rajgir"] },
      { name: "Nawada", cities: ["Nawada"] },
      { name: "Patna", cities: ["Patna", "Danapur", "Phulwari Sharif"] },
      { name: "Purnia", cities: ["Purnia"] },
      { name: "Rohtas", cities: ["Sasaram", "Dehri"] },
      { name: "Saharsa", cities: ["Saharsa"] },
      { name: "Samastipur", cities: ["Samastipur", "Dalsinghsarai"] },
      { name: "Saran", cities: ["Chapra", "Sonepur"] },
      { name: "Sheikhpura", cities: ["Sheikhpura"] },
      { name: "Sheohar", cities: ["Sheohar"] },
      { name: "Sitamarhi", cities: ["Sitamarhi"] },
      { name: "Siwan", cities: ["Siwan"] },
      { name: "Supaul", cities: ["Supaul"] },
      { name: "Vaishali", cities: ["Hajipur", "Mahnar"] },
      { name: "West Champaran", cities: ["Bettiah", "Narkatiaganj"] },
    ],
  },
  {
    name: "Chhattisgarh",
    districts: [
      { name: "Balod", cities: ["Balod"] },
      { name: "Baloda Bazar-Bhatapara", cities: ["Baloda Bazar", "Bhatapara"] },
      { name: "Balrampur", cities: ["Balrampur"] },
      { name: "Bastar", cities: ["Jagdalpur"] },
      { name: "Bemetara", cities: ["Bemetara"] },
      { name: "Bijapur", cities: ["Bijapur"] },
      { name: "Bilaspur", cities: ["Bilaspur", "Ratanpur"] },
      { name: "Dantewada", cities: ["Dantewada", "Geedam"] },
      { name: "Dhamtari", cities: ["Dhamtari"] },
      { name: "Durg", cities: ["Durg", "Bhilai"] },
      { name: "Gariaband", cities: ["Gariaband"] },
      { name: "Gaurela-Pendra-Marwahi", cities: ["Pendra"] },
      { name: "Janjgir-Champa", cities: ["Janjgir", "Champa"] },
      { name: "Jashpur", cities: ["Jashpurnagar"] },
      { name: "Kabirdham", cities: ["Kawardha"] },
      { name: "Kanker", cities: ["Kanker"] },
      { name: "Kondagaon", cities: ["Kondagaon"] },
      { name: "Korba", cities: ["Korba"] },
      { name: "Koriya", cities: ["Baikunthpur"] },
      { name: "Mahasamund", cities: ["Mahasamund"] },
      { name: "Manendragarh-Chirmiri-Bharatpur", cities: ["Manendragarh"] },
      { name: "Mohla-Manpur-Ambagarh Chowki", cities: ["Mohla"] },
      { name: "Mungeli", cities: ["Mungeli"] },
      { name: "Narayanpur", cities: ["Narayanpur"] },
      { name: "Raigarh", cities: ["Raigarh"] },
      { name: "Raipur", cities: ["Raipur"] },
      { name: "Rajnandgaon", cities: ["Rajnandgaon"] },
      { name: "Sakti", cities: ["Sakti"] },
      { name: "Sarangarh-Bilaigarh", cities: ["Sarangarh"] },
      { name: "Sukma", cities: ["Sukma"] },
      { name: "Surajpur", cities: ["Surajpur"] },
      { name: "Surguja", cities: ["Ambikapur"] },
      { name: "Khairagarh-Chhuikhadan-Gandai", cities: ["Khairagarh"] },
    ],
  },
  {
    name: "Goa",
    districts: [
      { name: "North Goa", cities: ["Panaji", "Mapusa", "Ponda"] },
      { name: "South Goa", cities: ["Margao", "Vasco da Gama", "Quepem"] },
    ],
  },
  {
    name: "Gujarat",
    districts: [
      { name: "Ahmedabad", cities: ["Ahmedabad", "Sanand", "Dholka"] },
      { name: "Amreli", cities: ["Amreli", "Savarkundla"] },
      { name: "Anand", cities: ["Anand", "Khambhat"] },
      { name: "Aravalli", cities: ["Modasa"] },
      { name: "Banaskantha", cities: ["Palanpur", "Deesa"] },
      { name: "Bharuch", cities: ["Bharuch", "Ankleshwar"] },
      { name: "Bhavnagar", cities: ["Bhavnagar", "Mahuva"] },
      { name: "Botad", cities: ["Botad"] },
      { name: "Chhota Udepur", cities: ["Chhota Udepur"] },
      { name: "Dahod", cities: ["Dahod"] },
      { name: "Dang", cities: ["Ahwa"] },
      { name: "Devbhoomi Dwarka", cities: ["Khambhalia", "Dwarka"] },
      { name: "Gandhinagar", cities: ["Gandhinagar", "Kalol"] },
      { name: "Gir Somnath", cities: ["Veraval", "Somnath"] },
      { name: "Jamnagar", cities: ["Jamnagar", "Jodiya"] },
      { name: "Junagadh", cities: ["Junagadh", "Mangrol"] },
      { name: "Kheda", cities: ["Nadiad", "Kapadvanj"] },
      { name: "Kutch", cities: ["Bhuj", "Gandhidham", "Anjar"] },
      { name: "Mahisagar", cities: ["Lunawada"] },
      { name: "Mehsana", cities: ["Mehsana", "Visnagar"] },
      { name: "Morbi", cities: ["Morbi", "Wankaner"] },
      { name: "Narmada", cities: ["Rajpipla"] },
      { name: "Navsari", cities: ["Navsari", "Gandevi"] },
      { name: "Panchmahal", cities: ["Godhra"] },
      { name: "Patan", cities: ["Patan", "Sidhpur"] },
      { name: "Porbandar", cities: ["Porbandar"] },
      { name: "Rajkot", cities: ["Rajkot", "Gondal", "Jetpur"] },
      { name: "Sabarkantha", cities: ["Himatnagar", "Idar"] },
      { name: "Surat", cities: ["Surat", "Bardoli"] },
      { name: "Surendranagar", cities: ["Surendranagar", "Wadhwan"] },
      { name: "Tapi", cities: ["Vyara"] },
      { name: "Vadodara", cities: ["Vadodara", "Padra"] },
      { name: "Valsad", cities: ["Valsad", "Vapi", "Pardi"] },
    ],
  },
  {
    name: "Haryana",
    districts: [
      { name: "Ambala", cities: ["Ambala", "Ambala Cantt"] },
      { name: "Bhiwani", cities: ["Bhiwani", "Loharu"] },
      { name: "Charkhi Dadri", cities: ["Charkhi Dadri"] },
      { name: "Faridabad", cities: ["Faridabad", "Ballabgarh"] },
      { name: "Fatehabad", cities: ["Fatehabad", "Tohana"] },
      { name: "Gurugram", cities: ["Gurugram", "Sohna"] },
      { name: "Hisar", cities: ["Hisar", "Hansi"] },
      { name: "Jhajjar", cities: ["Jhajjar", "Bahadurgarh"] },
      { name: "Jind", cities: ["Jind", "Narwana"] },
      { name: "Kaithal", cities: ["Kaithal"] },
      { name: "Karnal", cities: ["Karnal", "Nilokheri"] },
      { name: "Kurukshetra", cities: ["Kurukshetra", "Thanesar", "Pehowa"] },
      { name: "Mahendragarh", cities: ["Narnaul", "Mahendragarh"] },
      { name: "Nuh", cities: ["Nuh", "Ferozepur Jhirka"] },
      { name: "Palwal", cities: ["Palwal"] },
      { name: "Panchkula", cities: ["Panchkula", "Kalka"] },
      { name: "Panipat", cities: ["Panipat", "Samalkha"] },
      { name: "Rewari", cities: ["Rewari", "Dharuhera"] },
      { name: "Rohtak", cities: ["Rohtak", "Sampla"] },
      { name: "Sirsa", cities: ["Sirsa", "Dabwali"] },
      { name: "Sonipat", cities: ["Sonipat", "Gohana"] },
      { name: "Yamunanagar", cities: ["Yamunanagar", "Jagadhri"] },
    ],
  },
  {
    name: "Himachal Pradesh",
    districts: [
      { name: "Bilaspur", cities: ["Bilaspur", "Ghumarwin"] },
      { name: "Chamba", cities: ["Chamba", "Dalhousie"] },
      { name: "Hamirpur", cities: ["Hamirpur"] },
      { name: "Kangra", cities: ["Dharamshala", "Kangra", "Palampur"] },
      { name: "Kinnaur", cities: ["Reckong Peo"] },
      { name: "Kullu", cities: ["Kullu", "Manali"] },
      { name: "Lahaul and Spiti", cities: ["Kaza", "Keylong"] },
      { name: "Mandi", cities: ["Mandi", "Sundernagar"] },
      { name: "Shimla", cities: ["Shimla", "Rampur", "Rohru"] },
      { name: "Sirmaur", cities: ["Nahan", "Paonta Sahib"] },
      { name: "Solan", cities: ["Solan", "Baddi", "Parwanoo"] },
      { name: "Una", cities: ["Una"] },
    ],
  },
  {
    name: "Jharkhand",
    districts: [
      { name: "Bokaro", cities: ["Bokaro Steel City", "Chas"] },
      { name: "Chatra", cities: ["Chatra"] },
      { name: "Deoghar", cities: ["Deoghar", "Madhupur"] },
      { name: "Dhanbad", cities: ["Dhanbad", "Jharia"] },
      { name: "Dumka", cities: ["Dumka"] },
      { name: "East Singhbhum", cities: ["Jamshedpur", "Ghatshila"] },
      { name: "Garhwa", cities: ["Garhwa"] },
      { name: "Giridih", cities: ["Giridih"] },
      { name: "Godda", cities: ["Godda"] },
      { name: "Gumla", cities: ["Gumla"] },
      { name: "Hazaribagh", cities: ["Hazaribagh"] },
      { name: "Jamtara", cities: ["Jamtara"] },
      { name: "Khunti", cities: ["Khunti"] },
      { name: "Koderma", cities: ["Koderma"] },
      { name: "Latehar", cities: ["Latehar"] },
      { name: "Lohardaga", cities: ["Lohardaga"] },
      { name: "Pakur", cities: ["Pakur"] },
      { name: "Palamu", cities: ["Daltonganj"] },
      { name: "Ramgarh", cities: ["Ramgarh"] },
      { name: "Ranchi", cities: ["Ranchi"] },
      { name: "Sahebganj", cities: ["Sahebganj"] },
      { name: "Seraikela Kharsawan", cities: ["Seraikela", "Kharsawan"] },
      { name: "Simdega", cities: ["Simdega"] },
      { name: "West Singhbhum", cities: ["Chaibasa"] },
    ],
  },
  {
    name: "Karnataka",
    districts: [
      { name: "Bagalkot", cities: ["Bagalkot", "Jamkhandi"] },
      { name: "Ballari", cities: ["Ballari", "Hospet"] },
      { name: "Belagavi", cities: ["Belagavi", "Gokak", "Chikodi"] },
      { name: "Bengaluru Rural", cities: ["Devanahalli", "Doddaballapur", "Nelamangala"] },
      { name: "Bengaluru Urban", cities: ["Bengaluru"] },
      { name: "Bidar", cities: ["Bidar", "Humnabad"] },
      { name: "Chamarajanagar", cities: ["Chamarajanagar", "Kollegal"] },
      { name: "Chikkaballapur", cities: ["Chikkaballapur", "Chintamani"] },
      { name: "Chikkamagaluru", cities: ["Chikkamagaluru", "Kadur"] },
      { name: "Chitradurga", cities: ["Chitradurga", "Hosadurga"] },
      { name: "Dakshina Kannada", cities: ["Mangaluru", "Puttur", "Bantwal"] },
      { name: "Davanagere", cities: ["Davanagere", "Harihar"] },
      { name: "Dharwad", cities: ["Dharwad", "Hubballi"] },
      { name: "Gadag", cities: ["Gadag", "Betageri"] },
      { name: "Hassan", cities: ["Hassan", "Arsikere"] },
      { name: "Haveri", cities: ["Haveri", "Ranebennur"] },
      { name: "Kalaburagi", cities: ["Kalaburagi", "Sedam"] },
      { name: "Kodagu", cities: ["Madikeri", "Virajpet"] },
      { name: "Kolar", cities: ["Kolar", "Malur"] },
      { name: "Koppal", cities: ["Koppal", "Gangavathi"] },
      { name: "Mandya", cities: ["Mandya", "Maddur"] },
      { name: "Mysuru", cities: ["Mysuru", "Nanjangud"] },
      { name: "Raichur", cities: ["Raichur", "Sindhanur"] },
      { name: "Ramanagara", cities: ["Ramanagara", "Channapatna"] },
      { name: "Shivamogga", cities: ["Shivamogga", "Bhadravati"] },
      { name: "Tumakuru", cities: ["Tumakuru", "Tiptur"] },
      { name: "Udupi", cities: ["Udupi", "Kundapura", "Karkala"] },
      { name: "Uttara Kannada", cities: ["Karwar", "Sirsi", "Kumta"] },
      { name: "Vijayanagara", cities: ["Hospet"] },
      { name: "Vijayapura", cities: ["Vijayapura", "Basavana Bagevadi"] },
      { name: "Yadgir", cities: ["Yadgir", "Shahapur"] },
    ],
  },
  {
    name: "Kerala",
    districts: [
      { name: "Alappuzha", cities: ["Alappuzha", "Cherthala", "Chengannur"] },
      { name: "Ernakulam", cities: ["Kochi", "Aluva", "Perumbavoor"] },
      { name: "Idukki", cities: ["Painavu", "Thodupuzha", "Munnar"] },
      { name: "Kannur", cities: ["Kannur", "Thalassery"] },
      { name: "Kasaragod", cities: ["Kasaragod", "Kanhangad"] },
      { name: "Kollam", cities: ["Kollam", "Karunagappally"] },
      { name: "Kottayam", cities: ["Kottayam", "Changanassery"] },
      { name: "Kozhikode", cities: ["Kozhikode", "Vadakara"] },
      { name: "Malappuram", cities: ["Malappuram", "Manjeri", "Perinthalmanna"] },
      { name: "Palakkad", cities: ["Palakkad", "Ottapalam"] },
      { name: "Pathanamthitta", cities: ["Pathanamthitta", "Adoor"] },
      { name: "Thiruvananthapuram", cities: ["Thiruvananthapuram", "Neyyattinkara"] },
      { name: "Thrissur", cities: ["Thrissur", "Chalakudy", "Kodungallur"] },
      { name: "Wayanad", cities: ["Kalpetta", "Sulthan Bathery"] },
    ],
  },
  {
    name: "Madhya Pradesh",
    districts: [
      { name: "Agar Malwa", cities: ["Agar Malwa"] },
      { name: "Alirajpur", cities: ["Alirajpur"] },
      { name: "Anuppur", cities: ["Anuppur", "Kotma"] },
      { name: "Ashoknagar", cities: ["Ashoknagar"] },
      { name: "Balaghat", cities: ["Balaghat"] },
      { name: "Barwani", cities: ["Barwani"] },
      { name: "Betul", cities: ["Betul"] },
      { name: "Bhind", cities: ["Bhind"] },
      { name: "Bhopal", cities: ["Bhopal"] },
      { name: "Burhanpur", cities: ["Burhanpur"] },
      { name: "Chhatarpur", cities: ["Chhatarpur"] },
      { name: "Chhindwara", cities: ["Chhindwara"] },
      { name: "Damoh", cities: ["Damoh"] },
      { name: "Datia", cities: ["Datia"] },
      { name: "Dewas", cities: ["Dewas"] },
      { name: "Dhar", cities: ["Dhar", "Pithampur"] },
      { name: "Dindori", cities: ["Dindori"] },
      { name: "Guna", cities: ["Guna"] },
      { name: "Gwalior", cities: ["Gwalior"] },
      { name: "Harda", cities: ["Harda"] },
      { name: "Hoshangabad", cities: ["Hoshangabad", "Itarsi"] },
      { name: "Indore", cities: ["Indore"] },
      { name: "Jabalpur", cities: ["Jabalpur"] },
      { name: "Jhabua", cities: ["Jhabua"] },
      { name: "Katni", cities: ["Katni"] },
      { name: "Khandwa", cities: ["Khandwa"] },
      { name: "Khargone", cities: ["Khargone"] },
      { name: "Maihar", cities: ["Maihar"] },
      { name: "Mandla", cities: ["Mandla"] },
      { name: "Mandsaur", cities: ["Mandsaur"] },
      { name: "Mauganj", cities: ["Mauganj"] },
      { name: "Morena", cities: ["Morena"] },
      { name: "Narsinghpur", cities: ["Narsinghpur"] },
      { name: "Neemuch", cities: ["Neemuch"] },
      { name: "Niwari", cities: ["Niwari"] },
      { name: "Pandhurna", cities: ["Pandhurna"] },
      { name: "Panna", cities: ["Panna"] },
      { name: "Raisen", cities: ["Raisen"] },
      { name: "Rajgarh", cities: ["Rajgarh", "Biaora"] },
      { name: "Ratlam", cities: ["Ratlam"] },
      { name: "Rewa", cities: ["Rewa"] },
      { name: "Sagar", cities: ["Sagar"] },
      { name: "Satna", cities: ["Satna"] },
      { name: "Sehore", cities: ["Sehore"] },
      { name: "Seoni", cities: ["Seoni"] },
      { name: "Shahdol", cities: ["Shahdol"] },
      { name: "Shajapur", cities: ["Shajapur"] },
      { name: "Sheopur", cities: ["Sheopur"] },
      { name: "Shivpuri", cities: ["Shivpuri"] },
      { name: "Sidhi", cities: ["Sidhi"] },
      { name: "Singrauli", cities: ["Singrauli", "Waidhan"] },
      { name: "Tikamgarh", cities: ["Tikamgarh"] },
      { name: "Ujjain", cities: ["Ujjain"] },
      { name: "Umaria", cities: ["Umaria"] },
      { name: "Vidisha", cities: ["Vidisha"] },
    ],
  },
  {
    name: "Maharashtra",
    districts: [
      { name: "Ahmednagar", cities: ["Ahmednagar", "Shrirampur", "Sangamner"] },
      { name: "Akola", cities: ["Akola", "Akot"] },
      { name: "Amravati", cities: ["Amravati", "Achalpur"] },
      { name: "Beed", cities: ["Beed", "Georai"] },
      { name: "Bhandara", cities: ["Bhandara"] },
      { name: "Buldhana", cities: ["Buldhana", "Khamgaon"] },
      { name: "Chandrapur", cities: ["Chandrapur", "Ballarpur"] },
      { name: "Chhatrapati Sambhajinagar", cities: ["Chhatrapati Sambhajinagar"] },
      { name: "Dharashiv", cities: ["Dharashiv"] },
      { name: "Dhule", cities: ["Dhule", "Shirpur"] },
      { name: "Gadchiroli", cities: ["Gadchiroli"] },
      { name: "Gondia", cities: ["Gondia"] },
      { name: "Hingoli", cities: ["Hingoli"] },
      { name: "Jalgaon", cities: ["Jalgaon", "Bhusawal"] },
      { name: "Jalna", cities: ["Jalna"] },
      { name: "Kolhapur", cities: ["Kolhapur", "Ichalkaranji"] },
      { name: "Latur", cities: ["Latur", "Udgir"] },
      { name: "Mumbai City", cities: ["Mumbai"] },
      { name: "Mumbai Suburban", cities: ["Andheri", "Borivali", "Kurla"] },
      { name: "Nagpur", cities: ["Nagpur", "Kamptee"] },
      { name: "Nanded", cities: ["Nanded", "Deglur"] },
      { name: "Nandurbar", cities: ["Nandurbar"] },
      { name: "Nashik", cities: ["Nashik", "Malegaon", "Manmad"] },
      { name: "Palghar", cities: ["Palghar", "Vasai", "Boisar"] },
      { name: "Parbhani", cities: ["Parbhani", "Gangakhed"] },
      { name: "Pune", cities: ["Pune", "Pimpri-Chinchwad", "Baramati"] },
      { name: "Raigad", cities: ["Alibag", "Panvel", "Pen"] },
      { name: "Ratnagiri", cities: ["Ratnagiri", "Chiplun"] },
      { name: "Sangli", cities: ["Sangli", "Miraj"] },
      { name: "Satara", cities: ["Satara", "Karad"] },
      { name: "Sindhudurg", cities: ["Sindhudurg", "Kudal"] },
      { name: "Solapur", cities: ["Solapur", "Pandharpur"] },
      { name: "Thane", cities: ["Thane", "Kalyan", "Bhiwandi"] },
      { name: "Wardha", cities: ["Wardha"] },
      { name: "Washim", cities: ["Washim"] },
      { name: "Yavatmal", cities: ["Yavatmal", "Pusad"] },
    ],
  },
  {
    name: "Manipur",
    districts: [
      { name: "Bishnupur", cities: ["Bishnupur"] },
      { name: "Chandel", cities: ["Chandel"] },
      { name: "Churachandpur", cities: ["Churachandpur"] },
      { name: "Imphal East", cities: ["Porompat"] },
      { name: "Imphal West", cities: ["Imphal"] },
      { name: "Jiribam", cities: ["Jiribam"] },
      { name: "Kakching", cities: ["Kakching"] },
      { name: "Kamjong", cities: ["Kamjong"] },
      { name: "Kangpokpi", cities: ["Kangpokpi"] },
      { name: "Noney", cities: ["Noney"] },
      { name: "Pherzawl", cities: ["Pherzawl"] },
      { name: "Senapati", cities: ["Senapati"] },
      { name: "Tamenglong", cities: ["Tamenglong"] },
      { name: "Tengnoupal", cities: ["Tengnoupal"] },
      { name: "Thoubal", cities: ["Thoubal"] },
      { name: "Ukhrul", cities: ["Ukhrul"] },
    ],
  },
  {
    name: "Meghalaya",
    districts: [
      { name: "East Garo Hills", cities: ["Williamnagar"] },
      { name: "East Jaintia Hills", cities: ["Khliehriat"] },
      { name: "East Khasi Hills", cities: ["Shillong"] },
      { name: "Eastern West Khasi Hills", cities: ["Mairang"] },
      { name: "North Garo Hills", cities: ["Resubelpara"] },
      { name: "Ri Bhoi", cities: ["Nongpoh"] },
      { name: "South Garo Hills", cities: ["Baghmara"] },
      { name: "South West Garo Hills", cities: ["Ampati"] },
      { name: "South West Khasi Hills", cities: ["Mawkyrwat"] },
      { name: "West Garo Hills", cities: ["Tura"] },
      { name: "West Jaintia Hills", cities: ["Jowai"] },
      { name: "West Khasi Hills", cities: ["Nongstoin"] },
    ],
  },
  {
    name: "Mizoram",
    districts: [
      { name: "Aizawl", cities: ["Aizawl"] },
      { name: "Champhai", cities: ["Champhai"] },
      { name: "Hnahthial", cities: ["Hnahthial"] },
      { name: "Khawzawl", cities: ["Khawzawl"] },
      { name: "Kolasib", cities: ["Kolasib"] },
      { name: "Lawngtlai", cities: ["Lawngtlai"] },
      { name: "Lunglei", cities: ["Lunglei"] },
      { name: "Mamit", cities: ["Mamit"] },
      { name: "Saiha", cities: ["Saiha"] },
      { name: "Saitual", cities: ["Saitual"] },
      { name: "Serchhip", cities: ["Serchhip"] },
    ],
  },
  {
    name: "Nagaland",
    districts: [
      { name: "Chumoukedima", cities: ["Chumoukedima"] },
      { name: "Dimapur", cities: ["Dimapur"] },
      { name: "Kiphire", cities: ["Kiphire"] },
      { name: "Kohima", cities: ["Kohima"] },
      { name: "Longleng", cities: ["Longleng"] },
      { name: "Mokokchung", cities: ["Mokokchung"] },
      { name: "Mon", cities: ["Mon"] },
      { name: "Niuland", cities: ["Niuland"] },
      { name: "Noklak", cities: ["Noklak"] },
      { name: "Peren", cities: ["Peren"] },
      { name: "Phek", cities: ["Phek"] },
      { name: "Shamator", cities: ["Shamator"] },
      { name: "Tseminyu", cities: ["Tseminyu"] },
      { name: "Tuensang", cities: ["Tuensang"] },
      { name: "Wokha", cities: ["Wokha"] },
      { name: "Zunheboto", cities: ["Zunheboto"] },
    ],
  },
  {
    name: "Odisha",
    districts: [
      { name: "Angul", cities: ["Angul", "Talcher"] },
      { name: "Balangir", cities: ["Balangir", "Titlagarh"] },
      { name: "Balasore", cities: ["Balasore", "Soro"] },
      { name: "Bargarh", cities: ["Bargarh"] },
      { name: "Bhadrak", cities: ["Bhadrak"] },
      { name: "Boudh", cities: ["Boudh"] },
      { name: "Cuttack", cities: ["Cuttack", "Choudwar"] },
      { name: "Deogarh", cities: ["Deogarh"] },
      { name: "Dhenkanal", cities: ["Dhenkanal"] },
      { name: "Gajapati", cities: ["Paralakhemundi"] },
      { name: "Ganjam", cities: ["Berhampur", "Chhatrapur"] },
      { name: "Jagatsinghpur", cities: ["Jagatsinghpur", "Paradeep"] },
      { name: "Jajpur", cities: ["Jajpur"] },
      { name: "Jharsuguda", cities: ["Jharsuguda"] },
      { name: "Kalahandi", cities: ["Bhawanipatna"] },
      { name: "Kandhamal", cities: ["Phulbani"] },
      { name: "Kendrapara", cities: ["Kendrapara"] },
      { name: "Kendujhar", cities: ["Kendujhar"] },
      { name: "Khordha", cities: ["Bhubaneswar", "Khordha"] },
      { name: "Koraput", cities: ["Koraput", "Jeypore"] },
      { name: "Malkangiri", cities: ["Malkangiri"] },
      { name: "Mayurbhanj", cities: ["Baripada"] },
      { name: "Nabarangpur", cities: ["Nabarangpur"] },
      { name: "Nayagarh", cities: ["Nayagarh"] },
      { name: "Nuapada", cities: ["Nuapada"] },
      { name: "Puri", cities: ["Puri"] },
      { name: "Rayagada", cities: ["Rayagada"] },
      { name: "Sambalpur", cities: ["Sambalpur"] },
      { name: "Subarnapur", cities: ["Sonepur"] },
      { name: "Sundargarh", cities: ["Sundargarh", "Rourkela"] },
    ],
  },
  {
    name: "Punjab",
    districts: [
      { name: "Amritsar", cities: ["Amritsar", "Ajnala"] },
      { name: "Barnala", cities: ["Barnala"] },
      { name: "Bathinda", cities: ["Bathinda", "Rampura Phul"] },
      { name: "Faridkot", cities: ["Faridkot", "Kotkapura"] },
      { name: "Fatehgarh Sahib", cities: ["Fatehgarh Sahib", "Mandi Gobindgarh"] },
      { name: "Fazilka", cities: ["Fazilka", "Abohar"] },
      { name: "Ferozepur", cities: ["Ferozepur", "Guru Har Sahai"] },
      { name: "Gurdaspur", cities: ["Gurdaspur", "Batala"] },
      { name: "Hoshiarpur", cities: ["Hoshiarpur", "Garhshankar"] },
      { name: "Jalandhar", cities: ["Jalandhar", "Nakodar"] },
      { name: "Kapurthala", cities: ["Kapurthala", "Phagwara"] },
      { name: "Ludhiana", cities: ["Ludhiana", "Khanna"] },
      { name: "Malerkotla", cities: ["Malerkotla"] },
      { name: "Mansa", cities: ["Mansa"] },
      { name: "Moga", cities: ["Moga"] },
      { name: "Mohali", cities: ["Mohali", "Kharar"] },
      { name: "Muktsar", cities: ["Muktsar", "Malout"] },
      { name: "Pathankot", cities: ["Pathankot"] },
      { name: "Patiala", cities: ["Patiala", "Rajpura"] },
      { name: "Rupnagar", cities: ["Rupnagar", "Anandpur Sahib"] },
      { name: "Sangrur", cities: ["Sangrur", "Sunam"] },
      { name: "Shahid Bhagat Singh Nagar", cities: ["Nawanshahr"] },
      { name: "Tarn Taran", cities: ["Tarn Taran"] },
    ],
  },
  {
    name: "Rajasthan",
    districts: [
      { name: "Ajmer", cities: ["Ajmer", "Kishangarh"] },
      { name: "Alwar", cities: ["Alwar", "Bhiwadi"] },
      { name: "Balotra", cities: ["Balotra"] },
      { name: "Banswara", cities: ["Banswara"] },
      { name: "Baran", cities: ["Baran"] },
      { name: "Barmer", cities: ["Barmer"] },
      { name: "Beawar", cities: ["Beawar"] },
      { name: "Bharatpur", cities: ["Bharatpur", "Deeg"] },
      { name: "Bhilwara", cities: ["Bhilwara", "Shahpura"] },
      { name: "Bikaner", cities: ["Bikaner"] },
      { name: "Bundi", cities: ["Bundi"] },
      { name: "Chittorgarh", cities: ["Chittorgarh", "Nimbahera"] },
      { name: "Churu", cities: ["Churu", "Sujangarh"] },
      { name: "Dausa", cities: ["Dausa"] },
      { name: "Deeg", cities: ["Deeg"] },
      { name: "Didwana-Kuchaman", cities: ["Didwana", "Kuchaman"] },
      { name: "Dholpur", cities: ["Dholpur"] },
      { name: "Dungarpur", cities: ["Dungarpur"] },
      { name: "Hanumangarh", cities: ["Hanumangarh"] },
      { name: "Jaipur", cities: ["Jaipur", "Amber", "Dudu"] },
      { name: "Jaisalmer", cities: ["Jaisalmer"] },
      { name: "Jalore", cities: ["Jalore", "Bhinmal", "Sanchore"] },
      { name: "Jhalawar", cities: ["Jhalawar"] },
      { name: "Jhunjhunu", cities: ["Jhunjhunu", "Pilani"] },
      { name: "Jodhpur", cities: ["Jodhpur"] },
      { name: "Karauli", cities: ["Karauli"] },
      { name: "Khairthal-Tijara", cities: ["Khairthal", "Tijara"] },
      { name: "Kota", cities: ["Kota"] },
      { name: "Kotputli-Behror", cities: ["Kotputli", "Behror"] },
      { name: "Nagaur", cities: ["Nagaur", "Merta City"] },
      { name: "Pali", cities: ["Pali"] },
      { name: "Phalodi", cities: ["Phalodi"] },
      { name: "Pratapgarh", cities: ["Pratapgarh"] },
      { name: "Rajsamand", cities: ["Rajsamand", "Nathdwara"] },
      { name: "Salumbar", cities: ["Salumbar"] },
      { name: "Sawai Madhopur", cities: ["Sawai Madhopur", "Gangapur City"] },
      { name: "Sikar", cities: ["Sikar"] },
      { name: "Sirohi", cities: ["Sirohi", "Mount Abu"] },
      { name: "Sri Ganganagar", cities: ["Sri Ganganagar", "Anupgarh"] },
      { name: "Tonk", cities: ["Tonk"] },
      { name: "Udaipur", cities: ["Udaipur"] },
    ],
  },
  {
    name: "Sikkim",
    districts: [
      { name: "East Sikkim", cities: ["Gangtok"] },
      { name: "North Sikkim", cities: ["Mangan"] },
      { name: "Pakyong", cities: ["Pakyong"] },
      { name: "Soreng", cities: ["Soreng"] },
      { name: "South Sikkim", cities: ["Namchi"] },
      { name: "West Sikkim", cities: ["Gyalshing"] },
    ],
  },
  {
    name: "Tamil Nadu",
    districts: [
      { name: "Ariyalur", cities: ["Ariyalur"] },
      { name: "Chengalpattu", cities: ["Chengalpattu", "Tambaram"] },
      { name: "Chennai", cities: ["Chennai"] },
      { name: "Coimbatore", cities: ["Coimbatore", "Mettupalayam"] },
      { name: "Cuddalore", cities: ["Cuddalore", "Neyveli"] },
      { name: "Dharmapuri", cities: ["Dharmapuri"] },
      { name: "Dindigul", cities: ["Dindigul"] },
      { name: "Erode", cities: ["Erode", "Gobichettipalayam"] },
      { name: "Kallakurichi", cities: ["Kallakurichi"] },
      { name: "Kancheepuram", cities: ["Kancheepuram"] },
      { name: "Kanyakumari", cities: ["Nagercoil", "Kanyakumari"] },
      { name: "Karur", cities: ["Karur"] },
      { name: "Krishnagiri", cities: ["Krishnagiri", "Hosur"] },
      { name: "Madurai", cities: ["Madurai"] },
      { name: "Mayiladuthurai", cities: ["Mayiladuthurai"] },
      { name: "Nagapattinam", cities: ["Nagapattinam"] },
      { name: "Namakkal", cities: ["Namakkal", "Rasipuram"] },
      { name: "Nilgiris", cities: ["Udhagamandalam", "Coonoor"] },
      { name: "Perambalur", cities: ["Perambalur"] },
      { name: "Pudukkottai", cities: ["Pudukkottai"] },
      { name: "Ramanathapuram", cities: ["Ramanathapuram", "Rameswaram"] },
      { name: "Ranipet", cities: ["Ranipet", "Arakkonam"] },
      { name: "Salem", cities: ["Salem"] },
      { name: "Sivaganga", cities: ["Sivaganga", "Karaikudi"] },
      { name: "Tenkasi", cities: ["Tenkasi"] },
      { name: "Thanjavur", cities: ["Thanjavur"] },
      { name: "Theni", cities: ["Theni", "Bodinayakanur"] },
      { name: "Thoothukudi", cities: ["Thoothukudi", "Tiruchendur"] },
      { name: "Tiruchirappalli", cities: ["Tiruchirappalli", "Srirangam"] },
      { name: "Tirunelveli", cities: ["Tirunelveli", "Palayamkottai"] },
      { name: "Tirupathur", cities: ["Tirupathur", "Vaniyambadi"] },
      { name: "Tiruppur", cities: ["Tiruppur"] },
      { name: "Tiruvallur", cities: ["Tiruvallur", "Avadi"] },
      { name: "Tiruvannamalai", cities: ["Tiruvannamalai"] },
      { name: "Tiruvarur", cities: ["Tiruvarur"] },
      { name: "Vellore", cities: ["Vellore", "Gudiyatham"] },
      { name: "Viluppuram", cities: ["Viluppuram"] },
      { name: "Virudhunagar", cities: ["Virudhunagar", "Sivakasi"] },
    ],
  },
  {
    name: "Telangana",
    districts: [
      { name: "Adilabad", cities: ["Adilabad"] },
      { name: "Bhadradri Kothagudem", cities: ["Kothagudem", "Bhadrachalam"] },
      { name: "Hanumakonda", cities: ["Hanumakonda"] },
      { name: "Hyderabad", cities: ["Hyderabad"] },
      { name: "Jagtial", cities: ["Jagtial"] },
      { name: "Jangaon", cities: ["Jangaon"] },
      { name: "Jayashankar Bhupalpally", cities: ["Bhupalpally"] },
      { name: "Jogulamba Gadwal", cities: ["Gadwal"] },
      { name: "Kamareddy", cities: ["Kamareddy"] },
      { name: "Karimnagar", cities: ["Karimnagar"] },
      { name: "Khammam", cities: ["Khammam"] },
      { name: "Kumuram Bheem Asifabad", cities: ["Asifabad"] },
      { name: "Mahabubabad", cities: ["Mahabubabad"] },
      { name: "Mahabubnagar", cities: ["Mahabubnagar"] },
      { name: "Mancherial", cities: ["Mancherial"] },
      { name: "Medak", cities: ["Medak"] },
      { name: "Medchal-Malkajgiri", cities: ["Medchal", "Malkajgiri"] },
      { name: "Mulugu", cities: ["Mulugu"] },
      { name: "Nagarkurnool", cities: ["Nagarkurnool"] },
      { name: "Nalgonda", cities: ["Nalgonda"] },
      { name: "Narayanpet", cities: ["Narayanpet"] },
      { name: "Nirmal", cities: ["Nirmal"] },
      { name: "Nizamabad", cities: ["Nizamabad"] },
      { name: "Peddapalli", cities: ["Peddapalli"] },
      { name: "Rajanna Sircilla", cities: ["Sircilla"] },
      { name: "Rangareddy", cities: ["Shamshabad", "Ibrahimpatnam"] },
      { name: "Sangareddy", cities: ["Sangareddy"] },
      { name: "Siddipet", cities: ["Siddipet"] },
      { name: "Suryapet", cities: ["Suryapet"] },
      { name: "Vikarabad", cities: ["Vikarabad"] },
      { name: "Wanaparthy", cities: ["Wanaparthy"] },
      { name: "Warangal", cities: ["Warangal"] },
      { name: "Yadadri Bhuvanagiri", cities: ["Bhuvanagiri"] },
    ],
  },
  {
    name: "Tripura",
    districts: [
      { name: "Dhalai", cities: ["Ambassa"] },
      { name: "Gomati", cities: ["Udaipur"] },
      { name: "Khowai", cities: ["Khowai"] },
      { name: "North Tripura", cities: ["Kailashahar"] },
      { name: "Sepahijala", cities: ["Bishalgarh"] },
      { name: "South Tripura", cities: ["Belonia"] },
      { name: "Unakoti", cities: ["Kailasahar"] },
      { name: "West Tripura", cities: ["Agartala"] },
    ],
  },
  {
    name: "Uttar Pradesh",
    districts: [
      { name: "Agra", cities: ["Agra", "Fatehabad"] },
      { name: "Aligarh", cities: ["Aligarh", "Khair"] },
      { name: "Ambedkar Nagar", cities: ["Akbarpur"] },
      { name: "Amethi", cities: ["Amethi", "Gauriganj"] },
      { name: "Amroha", cities: ["Amroha"] },
      { name: "Auraiya", cities: ["Auraiya"] },
      { name: "Ayodhya", cities: ["Ayodhya"] },
      { name: "Azamgarh", cities: ["Azamgarh"] },
      { name: "Baghpat", cities: ["Baghpat"] },
      { name: "Bahraich", cities: ["Bahraich"] },
      { name: "Ballia", cities: ["Ballia"] },
      { name: "Balrampur", cities: ["Balrampur"] },
      { name: "Banda", cities: ["Banda"] },
      { name: "Barabanki", cities: ["Barabanki"] },
      { name: "Bareilly", cities: ["Bareilly"] },
      { name: "Basti", cities: ["Basti"] },
      { name: "Bhadohi", cities: ["Gyanpur", "Bhadohi"] },
      { name: "Bijnor", cities: ["Bijnor", "Najibabad"] },
      { name: "Budaun", cities: ["Budaun"] },
      { name: "Bulandshahr", cities: ["Bulandshahr", "Khurja"] },
      { name: "Chandauli", cities: ["Chandauli"] },
      { name: "Chitrakoot", cities: ["Chitrakoot"] },
      { name: "Deoria", cities: ["Deoria"] },
      { name: "Etah", cities: ["Etah"] },
      { name: "Etawah", cities: ["Etawah"] },
      { name: "Farrukhabad", cities: ["Farrukhabad", "Fatehgarh"] },
      { name: "Fatehpur", cities: ["Fatehpur"] },
      { name: "Firozabad", cities: ["Firozabad"] },
      { name: "Gautam Buddha Nagar", cities: ["Noida", "Greater Noida"] },
      { name: "Ghaziabad", cities: ["Ghaziabad", "Loni"] },
      { name: "Ghazipur", cities: ["Ghazipur"] },
      { name: "Gonda", cities: ["Gonda"] },
      { name: "Gorakhpur", cities: ["Gorakhpur"] },
      { name: "Hamirpur", cities: ["Hamirpur"] },
      { name: "Hapur", cities: ["Hapur"] },
      { name: "Hardoi", cities: ["Hardoi"] },
      { name: "Hathras", cities: ["Hathras"] },
      { name: "Jalaun", cities: ["Orai"] },
      { name: "Jaunpur", cities: ["Jaunpur"] },
      { name: "Jhansi", cities: ["Jhansi"] },
      { name: "Kannauj", cities: ["Kannauj"] },
      { name: "Kanpur Dehat", cities: ["Akbarpur"] },
      { name: "Kanpur Nagar", cities: ["Kanpur"] },
      { name: "Kasganj", cities: ["Kasganj"] },
      { name: "Kaushambi", cities: ["Manjhanpur"] },
      { name: "Kheri", cities: ["Lakhimpur"] },
      { name: "Kushinagar", cities: ["Padrauna"] },
      { name: "Lalitpur", cities: ["Lalitpur"] },
      { name: "Lucknow", cities: ["Lucknow"] },
      { name: "Maharajganj", cities: ["Maharajganj"] },
      { name: "Mahoba", cities: ["Mahoba"] },
      { name: "Mainpuri", cities: ["Mainpuri"] },
      { name: "Mathura", cities: ["Mathura", "Vrindavan"] },
      { name: "Mau", cities: ["Mau"] },
      { name: "Meerut", cities: ["Meerut"] },
      { name: "Mirzapur", cities: ["Mirzapur"] },
      { name: "Moradabad", cities: ["Moradabad"] },
      { name: "Muzaffarnagar", cities: ["Muzaffarnagar"] },
      { name: "Pilibhit", cities: ["Pilibhit"] },
      { name: "Pratapgarh", cities: ["Pratapgarh"] },
      { name: "Prayagraj", cities: ["Prayagraj"] },
      { name: "Raebareli", cities: ["Raebareli"] },
      { name: "Rampur", cities: ["Rampur"] },
      { name: "Saharanpur", cities: ["Saharanpur"] },
      { name: "Sambhal", cities: ["Sambhal"] },
      { name: "Sant Kabir Nagar", cities: ["Khalilabad"] },
      { name: "Shahjahanpur", cities: ["Shahjahanpur"] },
      { name: "Shamli", cities: ["Shamli"] },
      { name: "Shrawasti", cities: ["Bhinga"] },
      { name: "Siddharthnagar", cities: ["Naugarh"] },
      { name: "Sitapur", cities: ["Sitapur"] },
      { name: "Sonbhadra", cities: ["Robertsganj"] },
      { name: "Sultanpur", cities: ["Sultanpur"] },
      { name: "Unnao", cities: ["Unnao"] },
      { name: "Varanasi", cities: ["Varanasi"] },
    ],
  },
  {
    name: "Uttarakhand",
    districts: [
      { name: "Almora", cities: ["Almora", "Ranikhet"] },
      { name: "Bageshwar", cities: ["Bageshwar"] },
      { name: "Chamoli", cities: ["Gopeshwar", "Joshimath"] },
      { name: "Champawat", cities: ["Champawat"] },
      { name: "Dehradun", cities: ["Dehradun", "Rishikesh", "Mussoorie"] },
      { name: "Haridwar", cities: ["Haridwar", "Roorkee"] },
      { name: "Nainital", cities: ["Nainital", "Haldwani"] },
      { name: "Pauri Garhwal", cities: ["Pauri", "Kotdwar"] },
      { name: "Pithoragarh", cities: ["Pithoragarh"] },
      { name: "Rudraprayag", cities: ["Rudraprayag"] },
      { name: "Tehri Garhwal", cities: ["New Tehri"] },
      { name: "Udham Singh Nagar", cities: ["Rudrapur", "Kashipur"] },
      { name: "Uttarkashi", cities: ["Uttarkashi"] },
    ],
  },
  {
    name: "West Bengal",
    districts: [
      { name: "Alipurduar", cities: ["Alipurduar"] },
      { name: "Bankura", cities: ["Bankura"] },
      { name: "Birbhum", cities: ["Suri", "Bolpur"] },
      { name: "Cooch Behar", cities: ["Cooch Behar", "Dinhata"] },
      { name: "Dakshin Dinajpur", cities: ["Balurghat"] },
      { name: "Darjeeling", cities: ["Darjeeling", "Siliguri", "Kurseong"] },
      { name: "Hooghly", cities: ["Chinsurah", "Serampore"] },
      { name: "Howrah", cities: ["Howrah", "Uluberia"] },
      { name: "Jalpaiguri", cities: ["Jalpaiguri"] },
      { name: "Jhargram", cities: ["Jhargram"] },
      { name: "Kalimpong", cities: ["Kalimpong"] },
      { name: "Kolkata", cities: ["Kolkata"] },
      { name: "Malda", cities: ["English Bazar"] },
      { name: "Murshidabad", cities: ["Berhampore", "Jangipur"] },
      { name: "Nadia", cities: ["Krishnanagar", "Ranaghat"] },
      { name: "North 24 Parganas", cities: ["Barasat", "Barrackpore"] },
      { name: "Paschim Bardhaman", cities: ["Asansol", "Durgapur"] },
      { name: "Paschim Medinipur", cities: ["Medinipur", "Kharagpur"] },
      { name: "Purba Bardhaman", cities: ["Bardhaman", "Kalna"] },
      { name: "Purba Medinipur", cities: ["Tamluk", "Haldia"] },
      { name: "Purulia", cities: ["Purulia"] },
      { name: "South 24 Parganas", cities: ["Alipore", "Baruipur"] },
      { name: "Uttar Dinajpur", cities: ["Raiganj"] },
    ],
  },
  {
    name: "Andaman and Nicobar Islands",
    districts: [
      { name: "Nicobar", cities: ["Car Nicobar"] },
      { name: "North and Middle Andaman", cities: ["Mayabunder", "Rangat"] },
      { name: "South Andaman", cities: ["Port Blair"] },
    ],
  },
  {
    name: "Chandigarh",
    districts: [{ name: "Chandigarh", cities: ["Chandigarh"] }],
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    districts: [
      { name: "Dadra and Nagar Haveli", cities: ["Silvassa"] },
      { name: "Daman", cities: ["Daman"] },
      { name: "Diu", cities: ["Diu"] },
    ],
  },
  {
    name: "Delhi",
    districts: [
      { name: "Central Delhi", cities: ["Karol Bagh", "Daryaganj"] },
      { name: "East Delhi", cities: ["Preet Vihar", "Laxmi Nagar"] },
      { name: "New Delhi", cities: ["Connaught Place", "Chanakyapuri"] },
      { name: "North Delhi", cities: ["Civil Lines", "Kamla Nagar"] },
      { name: "North East Delhi", cities: ["Seelampur", "Yamuna Vihar"] },
      { name: "North West Delhi", cities: ["Rohini", "Pitampura"] },
      { name: "Shahdara", cities: ["Shahdara", "Vivek Vihar"] },
      { name: "South Delhi", cities: ["Saket", "Hauz Khas"] },
      { name: "South East Delhi", cities: ["Kalkaji", "Sarita Vihar"] },
      { name: "South West Delhi", cities: ["Dwarka", "Vasant Kunj"] },
      { name: "West Delhi", cities: ["Rajouri Garden", "Janakpuri"] },
    ],
  },
  {
    name: "Jammu and Kashmir",
    districts: [
      { name: "Anantnag", cities: ["Anantnag", "Pahalgam"] },
      { name: "Bandipora", cities: ["Bandipora"] },
      { name: "Baramulla", cities: ["Baramulla", "Sopore"] },
      { name: "Budgam", cities: ["Budgam"] },
      { name: "Doda", cities: ["Doda"] },
      { name: "Ganderbal", cities: ["Ganderbal"] },
      { name: "Jammu", cities: ["Jammu"] },
      { name: "Kathua", cities: ["Kathua"] },
      { name: "Kishtwar", cities: ["Kishtwar"] },
      { name: "Kulgam", cities: ["Kulgam"] },
      { name: "Kupwara", cities: ["Kupwara"] },
      { name: "Poonch", cities: ["Poonch"] },
      { name: "Pulwama", cities: ["Pulwama"] },
      { name: "Rajouri", cities: ["Rajouri"] },
      { name: "Ramban", cities: ["Ramban"] },
      { name: "Reasi", cities: ["Reasi"] },
      { name: "Samba", cities: ["Samba"] },
      { name: "Shopian", cities: ["Shopian"] },
      { name: "Srinagar", cities: ["Srinagar"] },
      { name: "Udhampur", cities: ["Udhampur"] },
    ],
  },
  {
    name: "Ladakh",
    districts: [
      { name: "Kargil", cities: ["Kargil"] },
      { name: "Leh", cities: ["Leh"] },
    ],
  },
  {
    name: "Lakshadweep",
    districts: [{ name: "Lakshadweep", cities: ["Kavaratti"] }],
  },
  {
    name: "Puducherry",
    districts: [
      { name: "Karaikal", cities: ["Karaikal"] },
      { name: "Mahe", cities: ["Mahe"] },
      { name: "Puducherry", cities: ["Puducherry"] },
      { name: "Yanam", cities: ["Yanam"] },
    ],
  },
];

export function getStateNames(): string[] {
  return indiaLocations.map((state) => state.name).sort((a, b) => a.localeCompare(b));
}

export function getDistrictsForState(stateName: string): string[] {
  const state = indiaLocations.find(
    (s) => s.name.toLowerCase() === stateName.toLowerCase()
  );
  if (!state) return [];
  return state.districts.map((d) => d.name).sort((a, b) => a.localeCompare(b));
}

export function getCitiesForDistrict(stateName: string, districtName: string): string[] {
  const state = indiaLocations.find(
    (s) => s.name.toLowerCase() === stateName.toLowerCase()
  );
  if (!state) return [];
  const district = state.districts.find(
    (d) => d.name.toLowerCase() === districtName.toLowerCase()
  );
  if (!district) return [];
  return [...district.cities].sort((a, b) => a.localeCompare(b));
}
