import { z } from 'zod'

// Fields map 1:1 to POST /medical-representatives's body and are sent on
// submit. Password is generated by the backend and never collected here.
export const medicalRepFormSchema = z.object({
  fullName: z.string().min(1, 'Full name is required'),
  lastName: z.string().min(1, 'Last name is required'),
  email: z.string().email('Enter a valid email address'),
  phone: z.string().regex(/^\d{10}$/, 'Enter a valid 10-digit phone number'),
  country: z.string().min(1, 'Country code is required'),
  regionId: z.string().uuid('Select a region'),
})

export type MedicalRepFormValues = z.infer<typeof medicalRepFormSchema>

export const medicalRepFormDefaults: MedicalRepFormValues = {
  fullName: '',
  lastName: '',
  email: '',
  phone: '',
  country: '91',
  regionId: '',
}

/** Fields accepted by POST /medical-representatives. */
export interface MedicalRepApiPayload {
  fullName: string
  lastName: string
  email: string
  phone: string
  country: string
  regionId: string
}

export function toMedicalRepApiPayload(values: MedicalRepFormValues): MedicalRepApiPayload {
  return {
    fullName: values.fullName,
    lastName: values.lastName,
    email: values.email,
    phone: values.phone,
    country: values.country,
    regionId: values.regionId,
  }
}
